# Generated by Django 4.2.16 on 2025-12-31 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("study_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStudyStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cumulative_study_time",
                    models.FloatField(default=0.0, verbose_name="累计学习时长(h)"),
                ),
                (
                    "template_completion_rate",
                    models.FloatField(default=0.0, verbose_name="模板完成率(%)"),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
