# Generated by Django 3.2.25 on 2025-12-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_dashboard', '0002_userstudystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='doll_image',
            field=models.ImageField(blank=True, null=True, upload_to='doll_images/', verbose_name='自定义玩偶图片'),
        ),
    ]
