# Generated by Django 4.2.16 on 2026-01-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_dashboard", "0003_userprofile_doll_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studytemplate",
            options={"ordering": ["order", "created_at"]},
        ),
        migrations.AddField(
            model_name="studytemplate",
            name="order",
            field=models.IntegerField(
                default=0, help_text="数值越小，排序越靠前", verbose_name="排序顺序"
            ),
        ),
    ]
