# Generated by Django 3.2.25 on 2026-01-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_dashboard', '0004_alter_studytemplate_options_studytemplate_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogress',
            name='actual_text',
            field=models.TextField(blank=True, null=True, verbose_name='完成情况描述'),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
        migrations.AddField(
            model_name='templatemodule',
            name='target_type',
            field=models.CharField(choices=[('numeric', '数值型'), ('boolean', '布尔型'), ('text', '文本型')], default='numeric', max_length=10, verbose_name='目标值类型'),
        ),
    ]
