# Generated by Django 3.2.25 on 2026-01-03 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study_dashboard', '0005_auto_20260103_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprogress',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyprogress',
            unique_together=set(),
        ),
    ]
