# Generated by Django 3.2.25 on 2026-01-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_dashboard', '0006_auto_20260103_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemodule',
            name='target_type',
            field=models.CharField(choices=[('numeric', '可量化目标'), ('boolean', '完成判断'), ('text', '主观描述')], default='numeric', max_length=10, verbose_name='目标值类型'),
        ),
        migrations.AlterField(
            model_name='templatemodule',
            name='target_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='目标量(如100个/100分钟)'),
        ),
    ]
