# Generated by Django 3.2.25 on 2026-01-04 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_dashboard', '0007_auto_20260103_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100, verbose_name='板块名称')),
                ('chapter_names', models.TextField(help_text='JSON格式的章节名称列表', verbose_name='章节名称列表')),
                ('content', models.TextField(verbose_name='学习资料内容')),
                ('generate_type', models.CharField(choices=[('simple', '简略版'), ('detailed', '详细版')], default='simple', max_length=10, verbose_name='生成类型')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='study_dashboard.templatemodule')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
