# Generated by Django 3.2.25 on 2026-01-13 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_dashboard', '0009_aichathistory_aichatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytemplate',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='studytemplate',
            name='is_example',
            field=models.BooleanField(default=False, verbose_name='是否为示例模板'),
        ),
    ]
